### ISSUE TITLE
File-extensions configured in FlowUpload-Attribute are case sensitive

### ISSUE THREAD

**Issue by swanitzek** [Grummle/FlowUploadFilter#1]
The FlowUpload-Attribute allows to specify accepted file-extensions:

```c#
[HttpPost]
[FlowUpload("png", "jpg")]
[ActionName("Upload")]
public ActionResult Upload(FlowFile file)
{
return Json(new { derp = file.flowFilename });
}
```

If a file is with the name "example.jpg" is uploaded everything works fine. As soon as the file-extension is for example uppercase ("example.JPG") the file isn't accepted for upload and the response from the Upload-Method isn't delivered to the caller.

I tracked down the problem down to FlowChunk.cs. Around line 66 you'll find the following statement:

```c#
 if (rules.AcceptedExtensions.Count > 0 && rules.AcceptedExtensions.SingleOrDefault(x => x == FileName.Split('.').Last()) == null)
                errorMessages.Add(rules.AcceptedExtensionsMessage ?? "type");
```

This code should accept files where the extension has a different case.

**Comment by swanitzek** [comment]
I created a pull-requests a couple of seconds ago. It includes fixes for this problem and also introduces unit-tests for this case.

**Comment by Grummle** [comment]
Outstanding, I'll take a look at this as soon as I get home. Thanks!

**Comment by Grummle** [comment]
Pushed a new [Nuget](https://www.nuget.org/packages/FlowUploadFilter/) (1.0.1) as well.
